# Generated by Django 3.0.7 on 2020-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
        ('posts', '0002_post_author'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', through='likes.Like', to='posts.Post'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
